### ISSUE TITLE
哆来咪捕梦漏洞（bug）

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#105]
哆来咪bug：里香回合内弃牌，哆来咪捕梦让里香收回弃置的牌，然后里香回合结束时发动技能，杀不同势力的神神子，弃牌，结果哆来咪还能发动捕梦让里香收回弃置的牌。
此外在第二还是第三轮的时候，二妹回合内弃牌，哆来咪却无法发动捕梦、

[哆来咪bug.txt](https://github.com/lwtmusou/touhoukill/files/9666361/bug.txt)

**Comment by Fsu0413** [comment]
flag清除早了。。。。。
