### ISSUE TITLE
体力下限判断出现的问题

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#112]
1点体力，2点体力上限的云山，被装备着死神镰刀的甲使用【杀】攻击，【杀】指定目标后，甲发动死神镰刀，让云山的体力下限+1，然后云山发动“变幻”技能，扣减了1点体力上限，体力值未发生变动，却出现云山立即阵亡的情况，这不符合体力下限的有关规则：

体力下限是角色扣减体力后进入濒死的阈值，角色扣减体力后体力值低过这个阈值就会进入濒死。所有角色的体力下限默认为1。
单纯增加体力下限而不扣减体力是不会导致角色进入濒死状态的。
如果某角色的体力上限低于他的体力下限，那么在扣减体力后，会直接死亡，不进入濒死状态。
例如：A角色的体力值、体力下限和体力上限都为1，现在令他的体力下限+1，然后再扣减体力，这时候他的体力上限低于体力下限，会立即死亡。

![bug1](https://user-images.githubusercontent.com/38370168/202886164-70d4f399-c571-46b5-b134-709237a2d3f6.png)
![bug2](https://user-images.githubusercontent.com/38370168/202886168-28425d30-0d14-4e9f-af72-72a078f3d4ff.png)
![bug3](https://user-images.githubusercontent.com/38370168/202886170-343082dc-bebb-4fde-9dfc-1d5a6a689f05.png)

**Comment by Fsu0413** [comment]
但是失去体力上限后，体力上限小于体力下限就暴毙的设定是在体力下限刚刚实装的时候（2014年）就有的
（显然是因为在体力下限没实装的时候，有失去体力上限后体力上限不大于0就暴毙的设定，不大于0 = 小于1 = 小于下限，很合理吧？）

**Comment by MataraOkina** [comment]
> 但是失去体力上限后，体力上限小于体力下限就暴毙的设定是在体力下限刚刚实装的时候（2014年）就有的 （显然是因为在体力下限没实装的时候，有失去体力上限后体力上限不大于0就暴毙的设定，不大于0 = 小于1 = 小于下限，很合理吧？）

主要是当前概念需要体力值变动才会暴毙。如果需要调整概念的话，则需要进一步讨论了。

**Comment by MataraOkina** [comment]
体力下限概念更新：
角色进入濒死的界限。
角色扣减体力后若体力值低过这个界限就会进入濒死。但在体力上限低于下限的情况下扣减体力或体力上限会直接导致死亡。
所有角色的体力下限默认为1。

新增体力上限扣减后，若体力上限低于下限，则直接导致人物死亡。

此问题不再是问题。
