### ISSUE TITLE
游戏牌修改方案

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#116]
- [x] 已实装
- [x] 已测试

【调虎离山】 锦囊牌·非全体性的普通锦囊牌
使用时机：出牌阶段。
使用目标：一至两名其他角色。
作用效果：目标角色神隐，若如此做，其于此回合结束时解除神隐状态。

◆神隐的角色处于神隐状态（其不计入距离和座次的计算，不能使用牌，不是牌的合法目标，不进行伤害结算和体力流失结算）。

重铸时机：出牌阶段。
◆重铸：声明一张牌并将之置入处理区，然后将之置入弃牌堆，最后摸一张牌。

修改点：取消使用牌后的执行动作，增加重铸功能。
提议点：处于神隐状态的角色不能执行以失去体力为发动代价的技能（如【渴血】）。

**Comment by MataraOkina** [comment]
【光学迷彩】 装备牌·防具
装备技能：锁定技，当你受到伤害时，你防止之，然后弃置场上的一张防具牌。

修改点：技能重做，受伤时防伤，然后弃场上一张防具牌（保底是防伤后弃自己的防具）。

**Comment by lwtmusou** [comment]
调虎实装了，找时候测下

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

春息
建议定位类别修改成流动性的延时类锦囊牌。

出去了又回去了，跟闪电性质差不多。

**Comment by MataraOkina** [comment]
> 调虎实装了，找时候测下

没有问题

**Comment by MataraOkina** [comment]
> 调虎实装了，找时候测下

但是调虎状态仍然可以不扣血执行渴血效果
