### ISSUE TITLE
强欲魔理沙凭空弃置黑桃牌漏洞

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#119]
神灵庙魔理沙在实战中凭空弃置了黑桃牌，手牌数无变动。
[虚空弃置黑桃bug.txt](https://github.com/lwtmusou/touhoukill/files/12539032/bug.txt)

**Comment by Fsu0413** [comment]
0.10.7的神幽香和寅丸星有问题，会导致这个东西。
目前神幽香重做，寅丸星已修复。如果场上有神幽香或者寅丸星，这个issue就可以先关掉了。
