### ISSUE TITLE
测试版凭空使用别人的寒冰剑漏洞

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#122]
旧魔理沙回合内使用了早苗手里的寒冰剑

[测试服新bug可以用别人手里的寒冰箭.txt](https://github.com/lwtmusou/touhoukill/files/12539087/bug.txt)

**Comment by Fsu0413** [comment]
0.10.7的神幽香和寅丸星有问题，会导致这个东西。
目前神幽香重做，寅丸星已修复。如果场上有神幽香或者寅丸星，这个issue就可以先关掉了。
