### ISSUE TITLE
皮肤 bgm 不必单独下载

### ISSUE THREAD

**Issue by lwtmusou** [lwtmusou/touhoukill#16]
- [x] 通过自动更新的方式一次性下载（自动检测可以改手动检测？）

- [ ] 随时检测并下载（比如本局游戏中自己选择的角色，若没有皮肤，则背后自动下载）

**Comment by Fsu0413** [comment]
自动更新的设计也有问题，当时没考虑这种情况。
倒是可以把自动更新也放到安装包里，等我有时间研究研究

**Comment by Fsu0413** [comment]
哦对还有一个问题，选择随时检测下载的话，如果不能下载压缩包，会耗费比较高昂的流量费用
倒是可以通过自动更新一次性下载，0.9.9我看看能不能装

**Comment by lwtmusou** [comment]
能在打开程序时，一次性检测出本地和服务器的bgm文件有不同，一次性下载也行。
第二项「随时检测并下载」的必要性不高。

**Comment by Fsu0413** [comment]
一次性检测不太可能，目前我想的只是对照版本号而已
现有皮肤bgm在0.9.2之后没更新过，所以版本号暂时还是写成0.9.2，等之后更新再说更新的事。
