### ISSUE TITLE
国战扩将实装

### ISSUE THREAD

**Issue by lwtmusou** [lwtmusou/touhoukill#24]
【春】（Fs：我改了描述）
1 桑尼 1.5血 （身份也统一改成此版 3血）
折射:（原版）
xx（技能名找天子）：一名角色回复体力后，你可以令其摸一张牌。

2 露娜 1.5血  （身份也统一改成此版 3血）
捉弄:（原版）  
寂静（buff）：你于回合内对其他角色造成伤害后，若其存活，你可以选择包括其的至多x名其他角色，你与这些角色的距离于此回合内视为1。你于其他角色的回合内受到伤害后，你选择除其以外的至多x名角色，其与这些角色的距离于此回合内无限大。（x为你已损失体力且至少为1）

注：无限大，可以妥协。换个说法？

3 斯塔 1.5血  （身份也统一改成此版 3血）
感应:（原版）  <del>当其他角色回复体力后或受到伤害后，若其体力值与你相等，你可选择： 摸一张牌，或弃置其一张手牌。</del>
xx（技能名找天子）：其他角色使用锦囊牌指定目标时，你可失去1点体力，取消此牌的一名目标角色。

注：取消的是目标角色，自然和无邪无关。

**Comment by lwtmusou** [comment]
【夏】
夜雀 1.5血
夜歌（削弱）: 其他角色的出牌阶段开始时，若场上没有【乐不思蜀】，你可以将一张手牌当【乐不思蜀】对其使用。你以此法使用方块牌时，你摸一张牌。 
牢笼：（原版）

针妙丸（原版）

正邪 1.5血 （完全推重，身份国战统一改成推重版）
逆转:你使用杀指定目标后或被杀指定后，若是唯一目标，你可和其交换手牌。此杀结算后你与其交换手牌。 每阶段限一次。 
诡诈:你进入濒死状态时，你可以观看一名其他角色的手牌并获得其中的一张【桃】或【酒】。 

影狼 人鱼这一次暂不进国战

**Comment by lwtmusou** [comment]
【秋】
1 华扇 （原版）

2 萃香 主1.5血 副2血
醉月:（原版）
斗酒（实际是原版）：主将技，此武将牌上单独的阴阳鱼个数-1；当其他角色于其出牌阶段内使用【桃】或【酒】时，你可以摸一张牌并与其拼点，当你赢后，此牌无效，你回复1点体力，然后结束当前阶段。 
萃集（有修改）: 副将技，摸牌阶段，你可以少摸一张牌，你选择一项条件 【1一种花色】或【2基本牌】或【3非基本牌】，检索一张符合条件的牌并获得之。 

3 姬海棠果

快照:出牌阶段限一次，你可令一名角色视为对另一名角色使用【知己知彼】。你使用【知己知彼】可执行所有选项。
短焦:（原版）

**Comment by lwtmusou** [comment]
【冬】
1 乡长（原版） 
2 朱鹭子（原版） 
3 魅魔（原版）


珠帘组合：
桑尼- 斯塔   桑尼-露娜  露娜-斯塔
针妙丸-正邪
华扇-萃香  华扇-勇仪   萃香-勇仪    文-姬海棠
乡长-魔理沙  乡长-朱鹭子  魅魔-魔理沙

 不确认，需讨论：  华扇-灵梦

**Comment by Fsu0413** [comment]
桑尼技能名暂定贪吃，要改的话找天子
斯塔技能内部名暂定 stqxjn（“斯塔取消技能”的拼音首字母）

**Comment by Fsu0413** [comment]
【春】
1 桑尼 1.5血 （身份也统一改成此版 3血）
折射:（原版）
**贪吃** （暂定）（技能名找天子）：一名角色回复体力后，你可以令其摸一张牌。

2 露娜 1.5血 （身份也统一改成此版 3血）
捉弄:（原版）
寂静（buff）：你回合内对其他角色造成伤害后，你可以选择其（伤害目标）在内（死了怎么算？暂定任意角色，没有目标限制）的至多x名 **其他** 角色（自己和自己的距离能改吗？），你与这些角色的距离于此回合内视为1。
你于其他角色回合内受到伤害后，你选择其（伤害来源还是当前回合角色？按照描述的话是当前回合角色）以外至多x名角色，其（当前回合角色）与这些角色的距离于此回合内无限大。（x为你已损失体力且至少为1）

注：无限大，可以妥协。换个说法？
Fs：视为1000

3 斯塔 1.5血 （身份也统一改成此版 3血）
感应:（原版） 当其他角色回复体力后或受到伤害后，若其体力值与你相等，你可选择： 摸一张牌，或弃置其一张手牌。
Fs：原版并非选择，而是可选摸一张然后可选弃置其一张，暂保留原实装
**取一** （暂定，stqxjn）（技能名找天子）：其他角色使用锦囊牌 **指定目标** （时机修改，应该无伤大雅吧）时，你可失去1点体力（消耗！），取消此牌的一名目标角色。

注：取消的是目标角色，自然和无邪无关。
Fs：插入结算濒死，濒死插入濒死。。。。。

**Comment by lwtmusou** [comment]
寂静：你回合内对其他角色造成伤害后，你可以选择其在内的至多x名其他角色，你与这些角色的距离于此回合内视为1。
你于其他角色回合内受到伤害后，你选择其以外至多x名角色，其与这些角色的距离于此回合内无限大。（x为你已损失体力且至少为1）

faq：  「选择其在内的至多x名 」：  若其死亡，不能发动。
        你选择其（当前回合角色）以外至多x名角色，其（当前回合角色）与这些角色的距离于此回合内无限大。

**Comment by lwtmusou** [comment]
我直到会插濒死， 不过只要不出现 蕾拉这种本身就濒死还插入「使用牌」的，斯塔本身不可能濒死插濒死。
至于掉体力放cost， 是因为觉得对比「取消目标后掉体力」 ， 反正要插的，把cost明确了更好。

**Comment by Fsu0413** [comment]
mystia扔原技能里了

**Comment by Fsu0413** [comment]
seija也装完了

**Comment by Fsu0413** [comment]
按照自己的理解先装了（指效果值+2）

**Comment by lwtmusou** [comment]
hegemony.cpp相关你暂时不会动了吧。一些小修的部分，我看今天自己找时间修掉

**Comment by Fsu0413** [comment]
那我今天先不改了

**Comment by lwtmusou** [comment]
短焦要做和马术一样的处理，enablePlay时按按钮直接亮。 晚上改。
顺带吐槽 神子副将技本也该一样处理的。 不过由于同时兼具 triggeralbe 和 enablePlay，导致无法预亮切换。
enablePlay时按按钮直接亮的功能给做成了另一个按钮。

**Comment by lwtmusou** [comment]
诡诈调整后，送葬或许提前时机了。和渴血一样，单独作viewas

**Comment by Fsu0413** [comment]
送葬我改吧

**Comment by Fsu0413** [comment]
送葬改完了
