### ISSUE TITLE
ai 补充及确认

### ISSUE THREAD

**Issue by lwtmusou** [lwtmusou/touhoukill#25]
- [x] 桑尼
- [x] 露娜
- [x] 斯塔
- [x] 夜雀
- [x] 小碗
- [x] 正邪
- [x] 火猫
- [x] 华扇
- [x] 萃香
- [x] 姬海棠
- [x] 魅魔
- [x] 乡长
- [x] 朱路子

**Comment by Fsu0413** [comment]
搞定的先传吧
