### ISSUE TITLE
身份普版灵梦

### ISSUE THREAD

**Issue by lwtmusou** [lwtmusou/touhoukill#30]
4hp
绮想: 当牌因使用打出弃置以外的原因进入弃牌堆后，你可以令一名角色获得其中的红桃牌。
封魔: 一名角色于一个回合内首次使用基本牌时，你可以弃置一张手牌，令使用者判定，若结果为红色，此牌无效。
 （约等于对每名角色一回合限一次）
主公技【教主型替换】 -》 改为司马懿型代替

**Comment by Fsu0413** [comment]
已实装，未测试，测试后关闭

**Comment by lwtmusou** [comment]
应该ok了
