### ISSUE TITLE
阿吽 养精蓄锐修改

### ISSUE THREAD

**Issue by lwtmusou** [lwtmusou/touhoukill#34]
3hp
陀螺：当主公摸牌或回复体力时，你可横置人物牌或横置装备区的一张牌，然后摸一张牌。
寻佛： 你可以将红桃牌当【养精蓄锐】使用。

2 养精蓄锐改动。
【养精蓄锐】 锦囊牌·一次性的延时类锦囊牌
使用时机：出牌阶段。
使用目标：一名角色。
作用效果：目标角色判定，若结果不为黑桃，其跳过弃牌阶段。且结束阶段开始时，其摸两张牌。 

（东方化牌堆时准备给白莲）

**Comment by MataraOkina** [comment]
陀螺跟一技能有什么必要的关联嘛？一技能名还是叫“寻佛”，二技能叫“镇社”好了。

**Comment by MataraOkina** [comment]
有单说了，阿吽只改二技能，一技能不动。
寻佛: 锁定技，当主公摸牌（因此技能而摸牌的除外）或回复体力时，若你的手牌数小于五，你摸一张牌。 
镇社：你可以将红桃牌当【养精蓄锐】使用。

**Comment by lwtmusou** [comment]
应该没啥问题了
