### ISSUE TITLE
主公摩多罗 二童子改动

### ISSUE THREAD

**Issue by lwtmusou** [lwtmusou/touhoukill#35]
*（1）摩多罗4hp
秘神：你可横置人物牌或装备区的一张牌，视为使用【调虎离山】。
里季：你可横置上家或下家的装备区的一张牌，视为对其使用下列牌。
	若横置的装备类型为：   武器：知己知彼  防具：铁索 防御马：桃  进攻马：火杀 宝物：调虎
后光1：你的装备区的牌被弃置或横置时，你可令其他璋势力角色选择是否代替你执行同类操作。

（注：主公技前提，其他tkz角色要能够做同类操作。 比如全部装备已经横置，就不能代替你横置装备了）
----------------------------------------------

（2）尔子田里乃 3hp
鼓舞：当前回合角色使用普通锦囊牌指定其上家或下家为目标时，你可横置人物牌或装备区的一张牌，你令一名角色成为此牌的额外目标。
茗荷：你受到伤害后，你可视为对任意名角色使用【联军盛宴】。此牌对目标生效后，若其体力值大于你，其于本回合不能使用牌。 

（联军盛宴目标由自己指定）
（注：已成为目标的角色不能再成为目标，大乔流离结算两次的情况东方杀体系内暂不允许）
（注：联军盛宴对不处于异常状态的角色是无效的。类似桃园结义。 所以后续小尾巴需要耦合？）
-----------------------------------------------

（3）丁礼田舞 3hp
狂舞：当前回合角色使用基本牌指定其上家或下家为目标时，你可横置人物牌或装备区的一张牌，你令一名角色成为此牌的额外目标。
竹笹：你受到伤害后，你可视为对任意名角色使用【联军盛宴】。此牌对目标生效后，若目标体力值大于你，其失去一点体力。

**Comment by lwtmusou** [comment]
装备横置的自动回复规则本身修改为：

结束阶段，若你本回合未有装备横置，你回复所有装备区的装备。

**Comment by lwtmusou** [comment]
后光（改）：你使用牌对其他璋势力角色结算完毕后，你可令选择是否进入神隐状态。

给fs实装降低难度好了。

**Comment by MataraOkina** [comment]
“竹笹”的“笹”是日本汉字，不在中国汉字内，所以把“笹”改成“屉”（同义字）

**Comment by MataraOkina** [comment]
规范化描述
尔子田里乃
鼓舞：当目前回合角色使用普通锦囊牌指定其上家或下家为目标时，你可以横置人物牌或装备区里的一张牌，令一名角色成为此牌的额外目标。
茗荷：当你受到伤害后，你可以视为使用【联军盛宴】（使用目标改为：至少一名角色）。当此牌对一个目标生效后，若其体力值大于你，其于此回合内不能使用牌。

丁礼田舞
狂舞：当目前回合角色使用基本牌指定其上家或下家为目标时，你可以横置人物牌或装备区里的一张牌，令一名角色成为此牌的额外目标。
竹屉：当你受到伤害后，你可以视为使用【联军盛宴】（使用目标改为：至少一名角色）。当此牌对一个目标生效后，若其体力值大于你，其失去1点体力。

**Comment by Fsu0413** [comment]
已实装，未测试，测试后关闭

**Comment by Fsu0413** [comment]
装备重置已修改

**Comment by lwtmusou** [comment]
实测没问题，关闭此issue。但propmt等关联用户体验的部分可能需要另行改进。
