### ISSUE TITLE
年代记永琳在联机时不能在自己回合内发动药理

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#37]
单机可以发动，联机时不能发动。
这在很久以前就报过了

**Comment by MataraOkina** [comment]
但多次测试后发现这种情况是随机的，有时候可以发动，有时候不能发动

**Comment by MataraOkina** [comment]
导致的因素可能是发动人数、奇偶不同？

**Comment by Fsu0413** [comment]
问题出在Yaoli::triggerable上，判断的flag应该是yaoliselected而不是yaolieffected
不是直接改字母可以改的了的 等我下班改吧

**Comment by Fsu0413** [comment]
353b46fd175144a0af85f9d763829b70b4c5c924
