### ISSUE TITLE
拆分Room::askForUseCard

### ISSUE THREAD

**Issue by Fsu0413** [lwtmusou/touhoukill#4]
受影响技能：
青龙偃月刀（装备）
浴血（弗兰朵露）
待添加。。。

**Comment by BeginnerSlob** [comment]
- -这要怎么拆

**Comment by Fsu0413** [comment]
确实不好拆。。。不过真的得拆，不拆怎么写“XXX时机，你可以使用一张【杀】”之类的技能？
主要拆的是Room::useCard这个函数，把消耗和效果拆开

**Comment by Fsu0413** [comment]
我的理解有问题。。。关了
