### ISSUE TITLE
狂舞和鼓舞发动时无文本提示

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#40]
![狂舞和鼓舞发动后无文本提示](https://user-images.githubusercontent.com/38370168/104848335-719e7380-591f-11eb-8fb5-bb20341c94eb.png)
丁礼田舞成为杀的目标后，发动狂舞让别人成为杀的额外目标，但记录信息的文本框没有提示和指示线，导致别人不知道成为了额外目标，这个需要优化。
尔子田里乃的鼓舞应该也应该需要优化

**Comment by lwtmusou** [comment]
done
