### ISSUE TITLE
蝴蝶的蝶形不能触发的问题

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#42]
[蝴蝶扣血不摸牌.txt](https://github.com/lwtmusou/touhoukill/files/5826406/default.txt)
当主，第一次扣血不摸牌，之后却摸牌了。

**Comment by lwtmusou** [comment]
p->tag["diexingHp"] = p->getGeneral()->getMaxHp();

emm
fs的锅。 没考虑主公+1血
