### ISSUE TITLE
神鵺化身问题

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#43]
![断线重连后不显示化身](https://user-images.githubusercontent.com/38370168/105506956-9589fc80-5d05-11eb-98dd-18df3b843afc.png)
（第一次重连时没点断线重连）断线重连后神鵺没有显示化身。虽然能发动技能，但更新化身后仍旧不显示。

**Comment by MataraOkina** [comment]
而且化身框无法关闭

**Comment by MataraOkina** [comment]
![QQ图片20210218142940](https://user-images.githubusercontent.com/38370168/108315007-c6226080-71f5-11eb-8a73-3f4b71be885e.jpg)
神鵺化身问题补充：神鵺化身sp丧面秦心后，回合结束，换了这化身，但“面”不会置入弃牌堆。

**Comment by Fsu0413** [comment]
![神鵺](https://user-images.githubusercontent.com/38370168/111456821-6a92b680-8752-11eb-8fae-1bbc295b6849.png)

- [ ] 当前回合是神鵺上家 搞事⑨。霍青娥濒死求桃 然后就神鵺化身红美铃发动背水给【桃】，接着就善逝。然后背水好像还没消失。
神鵺在当回合同时使用了背水 善逝两个技能 当回合好像并没有亮出红美铃 然后后面有一个回合又发动了背水 说是红美铃并没从X里消失
