### ISSUE TITLE
火猫的怨灵或者是磁闪的bug

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#46]
联机中发现：火猫的怨灵发动后，别人用磁【闪】抵消，虽然有绑上的动画了，但实际火猫并没被绑上。这需要修复。

**Comment by Fsu0413** [comment]
绑上的动画是setPlayerProperty触发，有动画一定会有属性变化
示例图里，对火猫造成伤害的牌是火攻，是火属性伤害，本来就会解锁，所以实际上是锁上了又解锁了，没有问题

解锁是受到属性伤害 __结算完毕后__ ，而怨灵是受到伤害 __后__ ，比解锁时机早

![QQ图片20210220113441](https://user-images.githubusercontent.com/4150545/108582659-a2832580-736f-11eb-94af-cc63a989d6cf.gif)
