### ISSUE TITLE
游戏中标记数量文本问题

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#47]
在游戏中因为背景部分区域的颜色与人物技能的标记数量文本颜色相同，导致玩家无法看清标记的数量，这问题需要解决，使得标记的数字可见。

**Comment by Fsu0413** [comment]
这玩意的颜色是写死在ClientPlayer里的，除非对界面大面积重构否则很难解决。
实际上我倒是想考虑把标记放在Photo内部而不是在Photo旁边列出来。。。。。

**Comment by MataraOkina** [comment]
问题重复，关掉旧的。

**Comment by Fsu0413** [comment]
不应该是关掉新的吗
