### ISSUE TITLE
神鵺化身问题

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#51]
![神鵺](https://user-images.githubusercontent.com/38370168/111456821-6a92b680-8752-11eb-8fae-1bbc295b6849.png)

当前回合是神鵺上家 搞事⑨。霍青娥濒死求桃 然后就神鵺化身红美铃发动背水给【桃】，接着就善逝。然后背水好像还没消失。
神鵺在当回合同时使用了背水 善逝两个技能 当回合好像并没有亮出红美铃 然后后面有一个回合又发动了背水 说是红美铃并没从X里消失

**Comment by Fsu0413** [comment]
#43
