### ISSUE TITLE
新将

### ISSUE THREAD

**Issue by Fsu0413** [lwtmusou/touhoukill#53]
sp茨木华扇    体力上限：4   势力：外
[寻臂]：出牌阶段限一次，你可以重铸一至两张牌，以此法获得牌后，你可以展示之，若其中有【杀】或装备牌，你摸一张牌。
[完身]：限定技，出牌阶段，若你装备区里的牌数不小于你的体力值，你可以加1点体力上限，获得一个额外的回合，失去“寻臂”并获得“邪力”（**出牌阶段空闲时间点**，你可以横置装备区里的一张牌并视为使用【酒】）。

**Comment by Fsu0413** [comment]
@MataraOkina 我看你技能好像改了，issue你自己改一下吧

**Comment by MataraOkina** [comment]
sp茨木华扇    体力上限：5   势力：外
[酌志]：出牌阶段限一次，你可以弃置一张手牌，亮出牌堆顶四张牌并获得其中一张牌。若其中有装备牌或【杀】，你额外获得一张牌。
[完身]：限定技，出牌阶段，若你装备区里的牌数大于2，你可以减1点体力上限，获得一个额外的回合和“邪力”（出牌阶段，你可以横置装备区里的一张牌并视为使用【酒】）。

FAQ：
1.“酌志”是一次性获得牌的。获得牌后，剩余亮出的牌会置入弃牌堆。
2.“邪力”是出牌阶段空闲时间点发动的（与“醉月”技能相同），会检测这出牌阶段空闲时间点是否用过【酒】，没用过就可以发动。视为使用的【酒】会计入使用次数限制。
3.“邪力”的【酒】并不能在处于濒死状态时发动。
4.“邪力”横置装备牌是消耗，如果无装备牌可以横置，则不能发动“邪力”。

**Comment by MataraOkina** [comment]
测试结果：
1.“完身”发动后， “酌志”消失了（本意是保留的）；
2.“邪力”在出牌阶段空闲时间点能重复发动（本意是使用酒要检测使用次上限是否达到1，到1就不能发动“邪力”）；
3.“完身”符合条件后能反复发动（不符合限定技规定）。

**Comment by Fsu0413** [comment]
@MataraOkina 没啥问题就关了吧

**Comment by Fsu0413** [comment]
sp茨木华扇    体力上限：5   势力：外
[酌志]：出牌阶段限一次，你可以弃置一张手牌，亮出牌堆顶三张牌并获得其中一张牌，若选择了装备牌或【杀】，你额外获得一张牌。
[完身]：限定技，出牌阶段，若你装备区里的牌数大于2，你可以减1点体力上限，获得一个额外的回合和“邪力”（出牌阶段，你可以横置装备区里的一张牌并视为使用【酒】）。

削弱方案

**Comment by MataraOkina** [comment]
暂时可以这样。

**Comment by Fsu0413** [comment]
Close in favor of #63
