### ISSUE TITLE
图书削弱

### ISSUE THREAD

**Issue by Fsu0413** [lwtmusou/touhoukill#56]
合咒: 当你需要使用/打出任意基本牌或普通锦囊牌时（除【无懈可击】外），你可以声明之并将牌堆底的两张牌置入弃牌堆，若两张牌花色与类型均不同，你视为使用/打出声明的牌。每回合限一次。 

 花色改成颜色

**Comment by MataraOkina** [comment]
再考虑加一个手牌消耗？问一下群里的人。

**Comment by MataraOkina** [comment]
有单考虑回调再加修改，暂时不动。
