### ISSUE TITLE
删除Skill::matchAvailablePattern，改用Engine::getPattern

### ISSUE THREAD

**Issue by Fsu0413** [lwtmusou/touhoukill#58]
RT

**Comment by Fsu0413** [comment]
魔典爱丽丝会崩溃 待调查

**Comment by MataraOkina** [comment]
蕾拉满血时在自己出牌阶段空闲点不需要前提条件是需要使用【桃】，就能发动华音，这不符合本意。

**Comment by MataraOkina** [comment]
![蕾拉](https://user-images.githubusercontent.com/38370168/114499384-8c4f6280-9c58-11eb-9d24-f20ed19787f8.png)

**Comment by MataraOkina** [comment]
SP秦心在触发面灵弃牌或用面灵后会使自己掉线。

**Comment by MataraOkina** [comment]
其他测试目前均正常

**Comment by lwtmusou** [comment]
测试转化技（viewas）时，对应的都要过一遍能否泛化的被动响应，能触发的好像有神绮，还有谁来着？ 
另一些文字描述不是转化技，但技能实质要应用到viewas的也得测，sp玫红虫子这种。

**Comment by Fsu0413** [comment]
finished
