### ISSUE TITLE
请教关于一类触发视为技操作的问题

### ISSUE THREAD

**Issue by Kouchya** [lwtmusou/touhoukill#6]
假设有个技能的效果是: 准备阶段，你可以将一张手牌当作【杀】使用。那么游戏中执行到相应的Room::askForUseCard语句时，需要先点一下技能按钮，然后才能选中一张任意手牌。如果不点技能按钮就无法选中手牌。请问为什么会有这种限制？实现代码在哪？
另外，上述情况下弹出的提示框里没有操作提示; prompt中如果有冒号，那么冒号以后的部分会被直接无视，后接的%1这样的参数也没法传递了。要修正这些的话需要改哪些代码？

**Comment by lwtmusou** [comment]
拿你自己技能来说
room->askForUseCard(player,  pattern, prompt， blabla。。。。）
首先我先确认： “这个技能首先能否发动成功？”（不管是不是要自己去点技能按钮）

其次，askForUseCard这种被动触发，应该是系统自动默认点了按钮的。
为什么会有“先要点一下技能按钮” 没太明白。 所以先问下你技能能不能成功发动，是不是技能还没实现

**Comment by lwtmusou** [comment]
prompt 那个 
 应该是会按冒号split，除开首元素，后续的依次对应   translation 那里可以直接用  %src  %dest  %arg


至于这个冒号分割是在client那里，至于%src  %dest  %arg怎么义的，大概率是client.cpp 的 setPromptList
我一时想不起了。好久没摸过这个点了。

**Comment by lwtmusou** [comment]
具体用例，你比照一下 lang下面 th11的阿空耀斑翻译。

**Comment by Kouchya** [comment]
prompt冒号的问题解决了，之前不知道%src %dest这些是有顺序的。。。

以及“先要点一下按钮”的原因知道了，不是因为视为技部分视为一张游戏牌，而是有好多种不同的pattern都能关联到这个视为技上。。。比如我把视为技的isEnabledAtResponse部分写成return pattern.startsWith("@@foo-")，那么当程序执行到pattern以"@@foo-"打头的任何一个askForUseCard时，会需要先点一下技能按钮，才能再选牌。这是由哪边的代码控制的？

另外，我程序里会出现这种情况是因为每一次askForUseCard时要记录某张牌名，视为技viewAs返回的牌和这个记录的牌名有关，而我目前是让pattern包含牌名，再通过getCurrentCardUsePattern取出牌名的。有什么其他方法可以在保证pattern恒定的情况下记录特定信息的吗？（我还试过tag，结果闪退）

最后，为什么这种情况下的askForUseCard会没有操作提示。。。就是lang翻译中["~skillname"]那一项。。。

**Comment by lwtmusou** [comment]
emm。。。 
"@@foo-"打头的pattern   那个问题：
目测是 void RoomScene::updateStatus下的
https://github.com/lwtmusou/touhoukill/blob/9046978d468cadab638dfd36be061c4612299fef/src/ui/roomscene.cpp#L2720 
 这个正则了。

至于当时为啥是这样，我都没印象了（汗）
``

**Comment by lwtmusou** [comment]
“我程序里会出现这种情况是因为每一次askForUseCard时要记录某张牌名”

这个具体举一个例子我可能才更好解释？你看看是不是和这边的骚灵三姐妹【协奏】这个技能类似。你参考一下。


具体原因是：
因为ViewAs是客户端（对应ClinetPlayer 或者 基类Player）， 恐怕你记录card名称时，是在服务器端吧，因为tag没有通知客户端)。 
试试setProperty

**Comment by lwtmusou** [comment]
_“最后，为什么这种情况下的askForUseCard会没有操作提示。。。就是lang翻译中["~skillname"]那一项。。。”_

关于这个，首先确认一下 不是所有 askForUseCard都有都有这问题吧。  如果只是刚才那个 "@@foo-"打头的pattern  如此的话， 猜测是 没能成功截取到skillname

https://github.com/lwtmusou/touhoukill/blob/9046978d468cadab638dfd36be061c4612299fef/src/client/client.cpp#L1001
你去看看这附近

**Comment by Kouchya** [comment]
懂啦，已经解决了，谢谢>v<

**Comment by Fsu0413** [comment]
@@foo-xxx确实不能匹配
必须@@之后直接接技能名
