### ISSUE TITLE
神幽香朽叶放多张牌到牌堆底的UI需要改进

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#61]
![幽香](https://user-images.githubusercontent.com/38370168/114562736-5b475000-9ca1-11eb-8ab1-053b57963ae9.png)
牌都显示在牌堆顶，会误导玩家。应该将牌置于牌堆底下（当前不能把牌移动到下面的牌堆底）。

**Comment by Fsu0413** [comment]
要作图

**Comment by MataraOkina** [comment]
> 要作图

不做图了，神幽香削弱，只放一张“叶”
