### ISSUE TITLE
里香/依莉斯设计稿

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#62]
里香   势力：旧    称号：少女机师   体力上限：4
战车：锁定技，出牌阶段开始时，若“车”标记数：小于4，你获得1枚“车”标记，然后可以弃置一张牌，令一名装备区里有牌的其他角色将其一张装备牌交给你；不小于4，你于此阶段内：使用牌无距离限制且无视其他角色的防具和宝物。
祸祟：一名角色的回合结束时，若此回合内你的装备牌被弃置或你装备区有牌离开过，你可以视为对一名其他角色使用无视防具的【杀】。

FAQ：
1.里香手牌中的装备牌被弃置后，装备区里装备牌的更替，都能在回合结束时发动“祸祟”。
2.“战车”的无视宝物效果会使得其他角色在此回合内无法发动【宝塔】【车流木马】的技能。

**Comment by Fsu0413** [comment]
待测试

**Comment by MataraOkina** [comment]
> 待测试

伊利斯的技能存在问题
易幻的弃置的两个条件中，“非装备”正常，但“不具有伤害效果”这个条件没有起到限制，导致只需要弃置非装备的牌就可以发动易幻。需要修正，使两个条件同时成立。
无罪不能发动选项一的效果（无法选择牌）。

里香没问题

**Comment by MataraOkina** [comment]
貌似没问题了
