### ISSUE TITLE
部分情况存在不能指定额外的目标的问题

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#69]
![可能的问题](https://user-images.githubusercontent.com/38370168/137951899-c49cb1eb-f5d4-4224-8983-652ed0790da5.png)
成美在成为别人以逸待劳的目标时不能发动技能指定额外目标。SP摩多罗类似。

**Comment by Fsu0413** [comment]
已改，待确认

**Comment by MataraOkina** [comment]
没问题
