### ISSUE TITLE
请教一下WrappedCard是做什么的

### ISSUE THREAD

**Issue by Kouchya** [lwtmusou/touhoukill#7]
发现FilterSkill里用到了这个但不明白它的功能，以及很多地方装备牌的类型用的也是WrappedCard而不是Card, EquipCard或具体的某个subtype，请问这个WrappedCard的功能是什么？在代码中是怎么体现的？

**Comment by Fsu0413** [comment]
所有的实体牌只有在Engine里是原牌，其余都是WrappedCard
使用WrappedCard把原有的牌包了一层，为了随时可以在不修改此牌固有属性的时候修改牌面信息
