### ISSUE TITLE
古明地觉使用决斗砸脚，不能对伤害来源发动“想起”

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#77]
![bug1](https://user-images.githubusercontent.com/38370168/143385319-d0baee68-e84d-499e-987e-a92c083e0d2a.png)
古明地觉对其他角色使用【决斗】，决斗砸脚，不能对其发动技能“想起”，这不符合技能描述。

另提一嘴：blt表示魅魔决斗砸脚不能发动技能“魅灵”是符合本意的。不要解决觉的问题的同时又把魅魔的代码改了。

**Comment by Fsu0413** [comment]
damage.by_user不能判定

**Comment by lwtmusou** [comment]
其实，没记错的话，觉这个的本意也应该是其他角色使用牌造成的伤害才触发。damage.by_user就是我专门写的
不知道你们后续描述有怎么改过了。

**Comment by MataraOkina** [comment]
![image](https://user-images.githubusercontent.com/38370168/145805240-ed641c46-7c21-40aa-a32b-2d2ecd673d91.png)
【连怨灵也恐惧的少女——古明地觉】
势力：地
体力：3
编号：11001
设计：星野梦美☆

【想起】：当你或你攻击范围内的一名角色受到牌造成的伤害后，若来源是另一名角色且不是你，你可以展示来源的一张手牌：若与造成伤害的牌类别相同且其不是你，弃置之，你对其造成1点伤害；若否，其获得之。
【读心】：锁定技，你选择其他角色的手牌时，其手牌对你可见。
【护主】：主公技，当你成为【杀】的唯一目标时，你可令其他地势力角色依次选择是否将此【杀】转移给其。

注1：【想起】的描述中，“使用的牌”包括转化的牌以及视为使用的牌。“其”指“受到伤害的角色”。“若否”包括“若与造成伤害的牌类别不同”以及“其是你”两种情况。
注2：【读心】生效的时机包括：你使用【过河拆桥】或【顺手牵羊】时，你发动【寒冰剑】效果时，你发动【想起】时，或一些技能需要你弃置、获得、展示其他角色的牌时（例如【泛读】【戏画】）。
注3：你发动【护主】后，当有其他地势力角色选择将【杀】转移给其后，【护主】的结算终止。

按照0.8版本的觉来说，FAQ未提及决斗砸脚不能发动想起。因此，按字面意思，觉决斗砸脚是可以发动想起的。
