### ISSUE TITLE
武将技能调整稿

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#79]
sp茨木华扇    体力上限：4   势力：外
[酌志]：出牌阶段限一次，你可以将一张基本牌当【以逸待劳】使用（选择目标须含你）。此牌结算结束时，你展示一张手牌，然后获得一张与之类别相同的于此牌结算中置入弃牌堆的牌。
[完身]：觉醒技，结束阶段开始时，若你装备区里的牌数大于2，你减1点体力上限，获得一个额外回合和“邪力”（出牌阶段，你可以横置装备区里的一张牌并视为使用【酒】）。

修改点：酌志的技能消耗由原来的【杀】变成基本牌。
理由：实战中发现以【杀】为消耗，限制过大，因此改成基本牌来提高技能的发动频率和强度。

**Comment by MataraOkina** [comment]
依神女苑&依神紫苑    体力上限：4 势力：战
[俭奢]: 其他角色的结束阶段开始时，你可以令其选择一项（若你于此回合内没有受到过伤害或没有失去过牌，你须先弃置一张手牌）：将手牌弃置至一张，若如此做，其回复1点体力；或摸一张牌，然后失去1点体力。 
[极厄]: 锁定技，手牌数小于其已损失的体力值的其他角色于你的回合内不能使用或打出牌。 
[依神]: 主公技，锁定技，你与在其他战势力角色攻击范围内的其他角色的距离-1。 

修改点：将“若你于此回合内没有失去过手牌”改为“若你于此回合内没有受到过伤害或没有失去过牌”，增加了于此回合内受到过伤害就不需要弃置牌，和把失去手牌改为失去牌。
理由：实战中依神的强度明显低于游戏环境，代价过大导致不适应八人场，因此对不需要弃牌的情况做了扩展。设计者blt已同意加强。

**Comment by MataraOkina** [comment]
年代记SP莲子  体力上限：4 势力：外
[量子]: 锁定技，当你使用或打出基本牌或普通锦囊牌时，你选择一项：横置；或重置。当你使用普通锦囊牌时，若你处于连环状态，你重置。
[科学]: 若你处于连环状态，你于出牌阶段的空闲时间点使用的【杀】无距离限制且额外目标数无上限。

修改点：增加了“当你使用普通锦囊牌时，若你处于连环状态，你重置。”这一效果。
理由：实战中能廉价地全场锦囊，相比同类型的“奇术”发动难度来说是太简单了，因此需要有脑子点，让别人在全体【杀】还是全体锦囊上做抉择。呓语和blt对此稿表示肯定。

**Comment by MataraOkina** [comment]
东风谷早苗 体力上限：4 势力：风
祭仪: 摸牌阶段开始时，你可以放弃摸牌，若如此做，此回合结束时，你摸三张牌。 
奇迹: 你可以将最后一张手牌当任意基本牌或普通锦囊牌使用或打出。每阶段限一次。 

修改点：给早苗加一点体力上限，变成四血。
理由：加血加生存能力，另一种方向是增加摸牌，但那样更容易导致卡壳问题的出现，因此还是以加血为主。有单提出的加强点。

**Comment by Fsu0413** [comment]
待测试

**Comment by MataraOkina** [comment]
测试完毕，没有问题。
莲子的稿待以后拿出更好的方案再实装。
