### ISSUE TITLE
年代记莲子技能“量子”实际效果与描述不符问题

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#81]
![莲子1](https://user-images.githubusercontent.com/38370168/145587900-b034c22a-6e8d-4502-9943-821e43369a5c.jpg)
![莲子2](https://user-images.githubusercontent.com/38370168/145587905-e4d0567d-a91a-46cf-bdef-964e90d0607f.png)
文本描述里是“出牌阶段的空闲时间点”才给加额外目标的，现在程序里却允许这个时间点外额外指定目标，不符合本意。
科学: 若你处于连环状态，你于出牌阶段的空闲时间点使用的【杀】和普通锦囊牌无距离限制且额外目标数无上限。

**Comment by Fsu0413** [comment]
虽然可以改，但是框架本身有问题，可能还有隐患

**Comment by MataraOkina** [comment]
经过测试，目前没问题，如莲子出牌阶段内对响子用借刀杀人后，响子反过来对他用借刀杀人，此时莲子使用杀不能发动技能科学选额外目标
