### ISSUE TITLE
杖刀偶磨弓和神 帕秋莉之间产生的bug

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#84]
杖刀偶磨弓发动“领军”后，神帕秋莉响应时点击“贤石”，然后不能进行操作，点击取消会导致不能作为直到“领军”响应时间结束。

**Comment by Fsu0413** [comment]
@@LingjunOtherVS 是怎么match上贤石的
match不上，技能应该根本点不出来才对

**Comment by Fsu0413** [comment]
好家伙 isEnabledAtResponse里根本没match

**Comment by Fsu0413** [comment]
fixed
