### ISSUE TITLE
人物调整稿

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#87]
- [x] 已实装
- [x] 已测试

幽幽子   4血
死蝶: 出牌阶段结束时，你可以视为对一名手牌数小于你的角色使用【杀】。 
役灵: 其他角色的出牌阶段开始时，你可以弃置装备区里至少一张牌，摸等量的牌，令其于此阶段内拥有“死蝶”。
墨染: 主公技，当你受到伤害后，你可以令其他妖势力角色选择是否将其一张装备牌置入你装备区里（有一名选是时，终止余下角色的询问）。

修改点：修改一技能的发动时间点，改为出牌阶段结束时发动；二技能将发动时间点调整至别人的出牌阶段开始时，增加弃牌自由度，由所有装备改成至少一张；三技能重推。

**Comment by MataraOkina** [comment]
纯狐   4血
瑕秽: 当你造成或受到伤害后，你可以明置来源和受到伤害的角色中一至两名角色各的一张手牌。 
纯化: 当一名角色使用明置的基本牌或明置的普通锦囊指定角色为目标后，你可以根据其一张明置手牌或此牌的颜色改变此牌的效果：黑色“使用者对目标角色造成1点伤害”；红色“目标角色回复1点体力”。 
杀意: 主公技，当其他绀势力角色使用具有伤害效果的牌时，其可以令你选择是否成为此牌的使用者。 

修改点：加强二技能，去掉了二技能的“每阶段限一次”。
理由：由于阶段限一次的限制，自身积累的明牌无法一回合内爆发出去，强度发挥有限，因此做限制解封。待此加强后观察一段时间，若依旧弱势，则考虑加强一技能或主公技，提升明牌的频率（从根本解决问题）。

**Comment by MataraOkina** [comment]
年代记永琳 4血
药理: 每名角色的出牌阶段限一次，其可以弃置一张牌，若如此做，你可以摸一张牌，然后弃置一张牌，若弃置的这两张牌对应下列同一种分类，则当其于此阶段内使用下一张该类的牌指定目标时，触发相应效果：
基本：此牌的第一个效果值+1。
普通锦囊：其令一名角色成为此牌的额外目标或取消一个目标角色。
装备、延时类锦囊：其弃置一名角色的装备区和判定区里所有的牌。

修改点：强化的牌从很多张牌削减至一张，增益效果做了调整，且变成强制触发，进行了新的分类（不是按牌的类别分类）。
理由：原版过于全能，强度过高，因此需要紧急削弱。对很一半很离谱的效果做了调整，待此削弱后表现，再做结构调整优化。

**Comment by Fsu0413** [comment]
已实装技能已打勾

**Comment by MataraOkina** [comment]
神 风见幽香 4血
【朽叶】若你的人物牌上没有与之类别相同的“叶”，你可以使用弃牌堆中的梅花基本牌或梅花普通锦囊牌。以此法使用牌结算完毕后，你将之置于人物牌上，称为“叶” 。
【狂季】当你使用手牌结算完毕后，或当你受到伤害后，你可以选择一项：将牌堆顶的四张牌置入弃牌堆，或将所有“叶”以任意顺序置于牌堆底。

**Comment by MataraOkina** [comment]
蕾米莉亚  3血
命运: 当判定开始前或出牌阶段结束时，若你手牌数不大于你的体力上限，你可以观看牌堆顶两张牌并获得其中一张牌，反之你可以将一张手牌置于牌堆顶。 

修改点：新增蕾米莉亚自己出牌阶段结束时这一技能发动时机；对摸牌进行了限制，需要手牌数不大于体力上限才能看牌摸牌，如果大于了，就只能自己丢牌到牌堆顶进行改判。
仅修改此技能用于测试，其他技能不变。

**Comment by MataraOkina** [comment]
永江衣玖   体力上限：4
[雷羽]：你可以将红桃或黑桃牌当雷【杀】使用；当你受雷电伤害时，你可以防止此伤害，摸两张牌。
[示灾]：出牌阶段限一次，你可以判定，然后当你于此回合内使用与结果颜色相同的牌时，你须横置一名角色。

修改点：对技能进行了重做。

blt、车波、天明等人均表示同意。

**Comment by MataraOkina** [comment]
永江衣玖   体力上限：4
[雷羽]：你可以将红桃或黑桃牌当雷【杀】使用；当你受雷电伤害时，你可以防止此伤害，摸两张牌。
[示灾]：出牌阶段限一次，你可以判定，然后当你于此回合内使用与结果颜色相同的牌时，你须横置一名角色。

修改点：对技能进行了重做。

blt、车波、天明等人均表示同意。

**Comment by MataraOkina** [comment]
天邪鬼SP正邪    3血
天邪: 当一张基本牌或普通锦囊牌对你结算结束后，若此牌未对你生效，你可以摸两张牌，否则你可以弃置此牌使用者的一张牌。 
夺宝: 锁定技，当你使用牌对其他角色造成伤害后，你获得场上的一张牌；当你受到其他角色使用的牌造成的伤害后，若你装备区里有牌，你须将一张装备牌交给其。

修改点：
一技能摸牌从一张变成两张，弃牌的选择权从对方变成正邪自己。
二技能造伤拿牌增强到了从场上拿牌，正邪自己受伤给装备牌的主动权掌握在了自己手里（并且可以把手里的装备给攻击者，而不仅限于装备区里的）。

blt、车波等人表示同意。

**Comment by MataraOkina** [comment]
年代记SP莲子 4血
量子: 锁定技，当你使用或打出基本牌或锦囊牌时，你选择一项：横置；或重置。
科学: 若你处于连环状态，你于你的回合内与其他角色的距离-X（X为你于此回合内使用过的牌的次数），且在出牌阶段空闲时间点使用的【杀】和普通锦囊牌的额外目标数无上限。

修改点：
一技能新增使用锦囊牌可以触发。
二技能去掉用牌无距离限制，改成处于连环状态时，加回合内自己到其他人距离，其他不变。

如此修改，增加了sp莲子的灵活性，并以此为代价，失去用排无距离限制，改成类似吴懿的用牌加距离。这样做的好处是保留了玩家可以用没距离限制的锦囊指定全场的爽快，同时也减少了无脑顺手牵羊、杀全场的高方差情况出现。

呓语、blt、天明、车波、223等人表示同意。

**Comment by MataraOkina** [comment]
大盗魔理沙 3血
借走: 出牌阶段，你可以将一张牌当【顺手牵羊】使用（以此法使用黑桃牌无距离限制）。以此法使用非黑桃牌时，或获得装备区里的黑桃牌后，你结束当前阶段。
收藏: 弃牌阶段开始时，你可以展示至少一张花色不同的手牌，令你的手牌上限于此回合内等量增加。


修改点：
一技能改成转化顺手，并且转化黑桃牌，那么顺手就无距离限制，但如果转化非黑桃牌或者拿了别人装备区里的黑桃牌，魔理沙就会结束自己的出牌阶段。
二技能仅是简化描述，无实际内容变动。

blt、呓语、天明、223、车波等人表示同意。

**Comment by MataraOkina** [comment]
妖妖梦灵梦 4血
职责: 锁定技，摸牌阶段，你少摸一张牌，观看一名有手牌的其他角色的手牌并获得其中一张牌。
春息: 当你获得牌后，你可以展示其中一张红桃牌并选择一名有手牌的其他角色（其不能是此回合内以此法选择过的角色），获得其一张手牌。 

修改点：
一技能改成少摸一张牌，然后看别人并拿他的一张手牌。
二技能改成得红桃牌后拿别人一张手牌，但那个人不能是本回合内二技能已经选择过的人。

blt、呓语、天明、223、车波等人表示同意。

**Comment by MataraOkina** [comment]
神灵庙SP早苗 4血

私欲: 出牌阶段限一次，你可以将一至两张手牌交给一名其他角色。若如此做，此回合结束时，你可以观看其手牌并获得其中的等量的牌。 
奇术: 你使用最后的手牌无距离限制；出牌阶段内，若你使用的【杀】或普通锦囊牌是最后的手牌，你使用此牌的额外目标数无上限。 

修改点：
一技能交出牌的数量可以增加到两张，同时回合结束的时候可以选择收回或不收回牌。（选择收回的话才给看手牌）

blt、呓语、天明、223、车波等人表示同意。

**Comment by Fsu0413** [comment]
调整技能均已实装 有问题更新到这里我记录

**Comment by MataraOkina** [comment]
风见幽香   4血
威压：锁定技，当其他角色于你的回合内使用或打出基本牌或【无懈可击】时（除代替或替换判定牌时外），你令其选择一项：令此牌无效，或弃置一张与之牌名相同的牌。 
繁花：出牌阶段限一次，你可以将一张与场上一种花色相同的牌当不计次数且无距离限制的【杀】使用。

修改点：新增二技能，一技能未变。

注：幽香可以将自己装备区里的牌直接当杀使用。（因为幽香装备区里的牌符合场上的花色判定，可以直接当杀使用）

**Comment by MataraOkina** [comment]
sp正邪在对别人造成伤害时，别人阵亡了，那么正邪就不能拿场上的牌了。
此外别人对sp正邪用过河拆桥，正邪无懈成功，过河拆桥没生效，但正邪的一技能却是弃那个人的牌，而不是自己摸一张牌

**Comment by MataraOkina** [comment]
神幽香在木流牛马里放牌后可以触发技能“狂季”，这不符合本意
此外，翠香的AI出现循环重铸铁索连环的情况，跟神幽香的AI犯病时相同。

**Comment by Fsu0413** [comment]
AI我暂时不管

> 此外别人对sp正邪用过河拆桥，正邪无懈成功，过河拆桥没生效，但正邪的一技能却是弃那个人的牌，而不是自己摸一张牌
天邪的判定我没动过（印象中）

**Comment by MataraOkina** [comment]
露米娅 3血
真夜: 出牌阶段限一次，你可以翻面并令一名其他角色选择一项：1.摸X张牌（X为其已损失的体力值且至少为1，至多为3），然后翻面；2.展示X张牌，令你获得其中的黑色牌，然后弃置其余的牌。
暗域: 当你成为黑色牌的目标后，你可以摸一张牌或翻面。 

修改点：
真夜重做，选项二必须拥有至少X张牌（包括装备区里的牌）才能被选，且弃置的执行者是被露米娅选择的人。
暗域时机调整。

**Comment by MataraOkina** [comment]
大妖精  3血
具现: 当你进入濒死状态时，你可以翻面，然后若你人物牌正面朝下，你亮出牌堆顶的三张牌（存活角色数小于4时，改为一张），选择一种花色，获得其中与此花色不同的牌，将其余的牌置入弃牌堆并回复等量的体力。 
半月: 出牌阶段限一次，你可以令一至三名角色各摸一张牌，然后若此次选择了至少两名角色，你失去1点体力。

修改点：
具现只要进濒死就可以翻面，但只有翻完后武将牌正面朝下才可以亮牌回血。在残局的情况下，亮出的牌会减少到一张。
半月将代价后置了（都摸完牌之后才判定），并且只让一个人摸牌是不用支付代价的。

**Comment by MataraOkina** [comment]
桑尼  3血
折射: 当你受到伤害时，若来源不是你，你可以弃置一张手牌并选择一名角色，防止此伤害，然后对其造成1点伤害，若如此做，当其因此而受到伤害进行的伤害结算结束时，其摸X张牌（X为其已损失的体力值）。 
助戏: 当一名角色回复体力后，你可以令其摸一张牌。

修改点：折射的消耗从一张手牌变成了一张红色手牌。
削弱桑尼转伤的稳定性。

**Comment by MataraOkina** [comment]
强欲魔理沙在未知情况下会导致自己回合的摸牌阶段发动强欲后本应该弃置两张牌，结果却变成直接弃三张牌，这不符合本意。
问题出现情况在魔理沙的第三个回合
[V0.10.7 神灵庙SP魔理沙(反贼)-20220917222631.txt](https://github.com/lwtmusou/touhoukill/files/9591965/V0.10.7.SP.-20220917222631.txt)

**Comment by Fsu0413** [comment]
> 

Fs看过这个录像之后表示不知道怎么回事

**Comment by Fsu0413** [comment]
> 强欲魔理沙在未知情况下会导致自己回合的摸牌阶段发动强欲后本应该弃置两张牌，结果却变成直接弃三张牌，这不符合本意。 问题出现情况在魔理沙的第三个回合 [V0.10.7 神灵庙SP魔理沙(反贼)-20220917222631.txt](https://github.com/lwtmusou/touhoukill/files/9591965/V0.10.7.SP.-20220917222631.txt)

Fs看过这个录像之后表示不知道怎么回事

**Comment by Fsu0413** [comment]
不管怎么说这个设置mark的条件我还是先改一下吧
目前是谁回合结束后重置谁的mark，暂时改成回合开始重置所有人的mark好了

**Comment by MataraOkina** [comment]
- [ 已实装 ] 
- [ 已测试 ] 

三月精SP琪露诺   3血
寻事: 锁定技，当其他角色使用【杀】或【桃】或普通锦囊牌指定目标时，若其体力值和手牌数均不小于你，你摸一张牌并成为额外目标。 
急冻: 当你成为【杀】或【决斗】的目标后，你可以弃置一张基本牌，令此牌的使用者选择一项：弃置一张点数大于你弃置的牌的手牌；或令此牌对你无效。 

改动点：对寻事进行了削弱，摸牌成为额外目标的条件改成“若其体力值和手牌数均不小于你”。
二技能不变。

**Comment by MataraOkina** [comment]
戎璎花 3血
【善垒】锁定技，准备阶段开始时，若你的手牌数大于你的手牌上限，你将手牌弃置至上限；结束阶段开始时，若你不是手牌数唯一最多的角色，你将手牌摸至X张（X为手牌最多的角色的手牌数+1）。 
【崩落】一名角色的结束阶段开始时，若你于此回合内不因使用而失去过手牌，你可以使用一张非锦囊牌。

改动点：善垒微调弃置、摸牌的时间点，并优化描述。崩落技能重做。

**Comment by MataraOkina** [comment]
牛崎润美 4血
【沦溺】其他角色的出牌阶段开始时，你可以将你装备区里的一张牌置入其装备区（若已有同类型的牌则替换之），若如此做，此阶段结束时，其获得其装备区里所有的牌。
【撩罟】当其他角色于其弃牌阶段弃置牌后，你可以使用这些牌中的一张牌，然后若你于回合内未曾失去过牌，你须弃置一张牌。

改动点：沦溺技能发动时间点微调，而二技能推倒重做。

**Comment by MataraOkina** [comment]
庭渡久侘歌 3血
【血岭】当你于出牌阶段外不以此法而失去牌后，你可以明置、横置或弃置你区域里的一张牌，然后若你各区域里不处于异常状态的牌数均不大于1，你摸两张牌。
【遗翎】当你的手牌被暗置，或装备牌被重置时，你可以将之交给一名其他角色。

改动点：技能全部推倒重做。

**Comment by MataraOkina** [comment]
杖刀偶磨弓 4血
【军阵】一名角色的出牌阶段结束时或死亡时，其可以将至少一张装备牌置入另一名角色的装备区里（两者中须有你），若如此做，后者可以将一将其一张牌当【杀】使用。
【瓷偶】锁定技，当你受到伤害时，若你受到的不是非转化牌造成的无属性伤害，此伤害值-1。

改动点：技能全部推倒重做。
注意，一技能选人的时候，要么是有“军阵”技能的人选别人，要么是别人选“军阵”技能的人。（考虑到神鵺、依姬获得的技能）

**Comment by MataraOkina** [comment]
埴安神袿姬 4血
【缮形】当一名角色失去装备区里的牌后，你可以令其摸一张牌，若如此做，其可以交给你一张手牌。
【灵守】结束阶段开始时，你可以观看一名角色的手牌并展示其中至多两张花色相同的牌，令其选择将这些牌重铸或当【杀】使用。 
【祷应】主公技，当其他鬼势力角色杀死一名角色后或死亡时，其可以令你回复1点体力。

改动点：灵守不变，其余技能重推。

**Comment by MataraOkina** [comment]
骊驹早鬼 4血
【天行】一名角色的出牌阶段结束时，若你攻击范围内的角色数与此阶段开始时不同，你可以视为使用无视距离的幻【杀】。
【劲疾】锁定技，你与其他角色的距离-1，且其他角色与你的距离+1；当你你使用或打出基本牌时，此技能于此回合内无效。

改动点：两个技能均重推。

**Comment by MataraOkina** [comment]
神子   4血
圣格: 觉醒技，准备阶段开始时，若你是手牌数唯一最少的角色或你没有手牌，你减1点体力上限，摸三张牌。 
倾听: 出牌阶段限一次，你可以令有手牌的所有其他角色各将一张手牌交给你（“圣格”发动后，改为你获得这些角色各一张手牌），然后你交给这些角色各一张手牌。 

改动点：觉醒技多了一个“若你是手牌数唯一最少的角色”条件，使得觉醒更容易了。其余技能不变。

**Comment by MataraOkina** [comment]
爱塔妮缇拉尔瓦   3血
蝶形: 锁定技，当你受到伤害后，你摸两张牌；当你一次性失去至少两张手牌后，你回复1点体力。 
鳞洒: 出牌阶段限一次，你可以将一张手牌交给一名其它角色并展示之，若此牌花色为：♥牌，其失去1点体力；♠牌，其于此回合内使用下一张手牌时，你无效之。 

改动点：蝶形扣体力摸牌改成受到伤害后摸牌。其他不变

**Comment by Fsu0413** [comment]
> 【崩落】一名角色的结束阶段开始时，若你于此回合内不因使用而失去过手牌，你可以使用一张非锦囊牌。

有歧义暂时放置

**Comment by MataraOkina** [comment]
> > 【崩落】一名角色的结束阶段开始时，若你于此回合内不因使用而失去过手牌，你可以使用一张非锦囊牌。
> 
> 有歧义暂时放置

不因为使用而失去过手牌，即有失去过手牌的情况，并且还不是因为使用导致的。

**Comment by MataraOkina** [comment]
爱莲   势力：旧   称号：空白少女   体力上限：3
空白： 一名角色的非额外回合结束时，若你于此回合内失去过牌，你可以令一名此回合内失去牌数量唯一最多的角色获得一个额外的回合，然后若其不为你，你失去1点体力。
魔偶：当你受到1点伤害后，你可以弃置一名角色一至两张牌，令其摸等量的牌（若其为你，你多摸一张牌）。

**Comment by MataraOkina** [comment]
萨拉 势力：旧 称号：魔界门番   体力上限：3
魔卫：当与你距离为1或势力与你相同的其他角色成为另一名其他角色使用具有伤害效果的牌的唯一目标时，你可以获得前者一张手牌，将该目标转移给你，然后你可以将一张牌交给前者。
门哨：当黑色【杀】或黑色普通锦囊牌对你结算完毕后，若你下列一个数值于此牌效果结算中未发生变化，你可以执行相应效果，若执行了两项效果，你可以弃置场上一张牌：手牌数——回复1点体力；体力值——摸一张牌。每回合限一次。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

梦子   4血
幻术: 当其他角色使用的基本牌或普通锦囊牌对你结算结束后，你可以获得此牌并明置之，每回合限一次。
奇刃: 你使用非转化的暗置手牌（装备牌或延时类锦囊牌除外）选择目标时，可以如使用你手牌里的一张明置手牌般地选择目标角色并暗置此明牌。每阶段限一次。

改动点：幻术变成可以自主发动，解放拿牌条件，但每回合限用一次。

**Comment by MataraOkina** [comment]
九十九弁弁   3血
余音: 当你受到伤害后，你可以获得一名体力值不小于你的角色的一张牌。 
无常: 当一名角色使用【杀】或黑色普通锦囊牌指定目标后，你可以令一名角色成为额外目标（检测合法性），然后若你不是此牌的目标，你受到其造成的1点伤害。

修改点：无常重做。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试


物部布都   3血
尸解: 一名角色的出牌阶段开始时，你可以弃置一张牌，展示牌堆一端的两张牌，若如此做，此阶段结束时，若其于此阶段内使用过的花色包含展示的花色，其可以回复1点体力或摸两张牌。
风水: 准备阶段开始时或判定开始前，你可以观看牌堆一端的三张牌，并改变其中任意数量的牌的顺序并将其余的牌以任意顺序置于牌堆另一端。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

云居一轮  3血
入道：当你使用牌指定其他角色为唯一目标时，或成为其他角色使用牌的唯一目标时，你可以取消此目标，令此牌的使用者摸两张牌，每回合限一次。
挥摧：结束阶段开始时，若你于此回合内没有造成过伤害，你可以弃置你攻击范围内一名角色装备区或判定区里的一张牌。

修改点：
两个技能全部重做。
一技能改成你对别人单用牌，或别人对你单用牌，你就可以取消这目标，来让用牌的人摸两张牌。
二技能是简单的拆牌技能。

blt、车波、七曜等人表示同意。

**Comment by MataraOkina** [comment]
雾雨魔理沙 4血
魔法: 出牌阶段限一次，你可以弃置一张牌，令你于此回合内使用的【杀】或普通锦囊牌的伤害值基数+1，若以此法弃置♠牌，你摸一张牌。 
雾雨: 主公技，其他角色的出牌阶段限一次，其可以将一张♠牌交给你。 

修改点：魔法的消耗从一张手牌改成一张牌。

蚊子腿加强，但总比没有好。

**Comment by MataraOkina** [comment]
绵月丰姬   4血
连系: 当你使用、打出或弃置【杀】时，你可以视为重铸或使用【铁索连环】。
月使: 觉醒技，准备阶段开始时，若你处于异常状态，你减1点体力上限，然后获得“睿智”（当普通锦囊牌对你结算结束时，若你已受伤，你可以判定，若结果为红色，你回复1点体力）。 

修改点：丰姬改成四血；一技能增加“弃置【杀】时”这个时机作为触发点；二技能觉醒技将加体力上限改成减体力上限。

正常的加强。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

冈崎梦美   4血
次元: 回合开始时，你可以交换此回合内的两个阶段的顺序。 
时轨: 摸牌阶段结束时或出牌阶段结束时，你可以将手牌调整至X张（X为此回合内你已执行的阶段数），若以此法：获得牌，你失去1点体力；弃置牌，你回复1点体力，然后此技能于此回合内无效。 

修改点：去除时轨回合限一次的限制，但回血后会导致技能在回合内无效。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

密封梦魇堇子 4血
梦乡: 你可以跳过出牌阶段，若如此做，此回合的弃牌阶段结束时，你可以选择X名角色（X为你于此阶段内弃置的牌的牌数），观看这些角色各手牌并可以使用各一张手牌，以此法使用非基本牌结算结束后，失去此牌的角色摸一张牌。 
记事: 当你的手牌因弃置而置入弃牌堆时，你可以将其中至少一张牌以任意顺序置于牌堆顶。 

修改点：梦乡的“以此法使用牌结算结束后”改成“以此法使用非基本牌结算结束后”，即用牌改成用非基本牌才摸一张牌。

提升sp堇子对敌发动技能的次数，选择更加平衡。

**Comment by MataraOkina** [comment]
吉吊八千慧   4血
【伪仪】出牌阶段限一次，你可以选择两名角色并令其中一名角色选择一项：1.对另一者使用【杀】（无距离限制）；2.将其一张牌交给你，当你获得后，你可以将之当【杀】对其使用。
【夺志】一名角色的准备阶段开始时，若其手牌数不小于你，你可以令一名手牌数小于你的角色摸一张牌，然后令后者于此回合内不能使用或打出【闪】。

修改点：技能重做。

**Comment by MataraOkina** [comment]
> * [x]  已实装
> * [x]  已测试
> 
> 爱塔妮缇拉尔瓦 3血 蝶形: 锁定技，当你受到伤害后，你摸两张牌；当你一次性失去至少两张手牌后，你回复1点体力。 鳞洒: 出牌阶段限一次，你可以将一张手牌交给一名其它角色并展示之，若此牌花色为：♥牌，其失去1点体力；♠牌，其于此回合内使用下一张手牌时，你无效之。
> 
> 改动点：蝶形扣体力摸牌改成受到伤害后摸牌，技能削弱，其他效果不变。

蝴蝶暂时适用这版，转化知己知彼的那版改动建议搁置，待改稿成型再实装。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试


八坂神奈子 4血
神德: 当你不以此法而使用或打出【杀】时，你可以摸一张牌，然后将一张手牌置于人物牌上，称为“神德”；你可以将两张“神德”当任意基本牌使用。
乾坤: 锁定技，你的手牌上限和攻击范围+1。 
供奉: 主公技，其他风势力角色的出牌阶段限一次，其可以将一张【杀】交给你。 

修改点：
1.神德可以变任意基本牌了，但这样变的杀不能触发前段效果。
2.乾坤让攻击范围也增加，但跟手牌上限一样只+1。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试


洩矢诹访子   3血
不输: 当你或一名在你攻击范围内的角色受到伤害后，若其存活，你可以与伤害来源拼点：当你赢后，你令其回复1点体力；当你没赢后，你获得来源的拼点牌。
乾坤: 锁定技，你的手牌上限和攻击范围+1。 
传承: 当你死亡时，你可以令一名其他角色获得“乾坤”和“传承”，然后其获得你区域里所有的牌。 

修改点：同神奈子乾坤一样的修改。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试


堇子 4血
念力: 出牌阶段限一次，你可以将牌堆顶的两张牌当【杀】或【顺手牵羊】使用。当你使用此牌指定目标后，若此牌无颜色，你失去1点体力，然后你可以将一张牌置于牌堆顶，使你于此阶段能再发动此技能转化此阶段未转化项。
深秘: 摸牌阶段摸牌后，你可以观看牌堆顶的三张牌并改变其中任意数量的牌的顺序。 
重身: 主公技，锁定技，你回合内，你与战势力角色攻击范围内的其他角色的距离视为1。


修改点：
1.一技能念力掉血后，追加可以放牌来增加一次发动次数的效果，但再发动只能转化这阶段还没转化过的。
2.二技能直接看牌堆顶，不再受手牌数量限制。
3.三技能改成拉近跟敌人的距离。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

神灵庙SP鵺 3血
不明: 出牌阶段限一次，你可以弃置一张牌并选择一名在你攻击范围内的角色，其须声明【杀】或【决斗】，然后你视为对其使用声明的牌。 
正体: 当你受到伤害后，你可以获得伤害来源装备区里的一张牌；当你受到伤害时，你可以将一张装备牌置入其他角色的装备区，将此伤害转移给其。 

修改点：
将原本限制过高的二技能进行重改，受伤可以得伤害来源的装备，再受伤时可以把装备给别人穿上，把伤害转给他。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

神 风见幽香 4血
朽叶: 若你的人物牌上没有与之类别相同的“叶”，你可以使用弃牌堆中的梅花基本牌或梅花普通锦囊牌。以此法使用的牌结算完毕后，你将之置于人物牌上，称为“叶”。 
狂季: 当你使用手牌结算完毕后，或当你受到伤害后，你可以选择一项：将牌堆顶的三张牌置入弃牌堆；或将一张“叶”置于牌堆底。 

修改点：
二技能削弱，置入弃牌堆的牌从四张变成三张，置入牌堆底的牌从全部变成放一张。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

神 风见幽香 4血
朽叶: 若你的人物牌上没有与之类别相同的“叶”，你可以使用弃牌堆中的梅花基本牌或梅花普通锦囊牌。以此法使用的牌结算完毕后，你将之置于人物牌上，称为“叶”。 
狂季: 当你使用手牌结算完毕后，或当你受到伤害后，你可以选择一项：将牌堆顶的三张牌置入弃牌堆；或将一张“叶”置于牌堆底。 

修改点：
二技能削弱，置入弃牌堆的牌从四张变成三张，置入牌堆底的牌从全部变成放一张。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

里香   4血
战车: 出牌阶段限一次，你可以弃置一张牌，令一名装备区里有牌的其他角色将其一张装备牌交给你，然后若你是装备区里牌数最多的角色，你于此回合内使用牌无距离限制。
祸祟: 一名角色的结束阶段开始时，若你于此回合内失去过装备区里的牌，你可以视为使用幻【杀】。 

修改点：去标记化，全部重推。

**Comment by MataraOkina** [comment]
- [ ] 已实装
- [ ] 已测试

依神女苑&依神紫苑    体力上限：4 势力：战
俭奢: 其他角色的结束阶段开始时，你可以弃置一张牌，令其选择一项：1.交给你一张牌；2.摸一张牌，然后失去1点体力。 
极厄: 出牌阶段限一次，你可以令至少一名手牌数小于其已损失体力值的角色各失去1点体力。
依神: 主公技，锁定技，当你成为【杀】的目标后，若此牌使用者攻击范围内有其他战势力角色，其选择弃置一张牌或令【杀】无效。

修改点：全部重推。

**Comment by MataraOkina** [comment]
> * [x]  已实装
> * [ ]  已测试
> 
> 杖刀偶磨弓 4血 【军阵】一名角色的出牌阶段结束时，其可以将至少一张装备牌置入另一名角色的装备区里（两者中须有你），若如此做，后者可以将其一张牌当【杀】使用。 
【瓷偶】锁定技，当你受到伤害时，若你受到的不是非转化牌造成的无属性伤害，此伤害值-1。
> 
> 改动点：技能全部推倒重做。 注意，一技能选人的时候，要么是有“军阵”技能的人选别人，要么是别人选“军阵”技能的人。（考虑到神鵺、依姬获得的技能）。死亡时发动军阵时，后者转化杀的时机要延后到前者死亡后才能执行，以规避不合理的结算插入。

实战中

> * [ ]  已实装
> * [ ]  已测试
> 
> 杖刀偶磨弓 4血 【军阵】一名角色的出牌阶段结束时，其可以将至少一张装备牌置入另一名角色的装备区里（两者中须有你），若如此做，后者可以将一张牌当【杀】使用。 【瓷偶】锁定技，当你受到伤害时，若你受到的不是非转化牌造成的无属性伤害，此伤害值-1。
> 
> 改动点：技能全部推倒重做。 注意，一技能选人的时候，要么是有“军阵”技能的人选别人，要么是别人选“军阵”技能的人。（考虑到神鵺、依姬获得的技能）。

瓷偶在测试中发现免疫所有伤害的漏洞。

**Comment by MataraOkina** [comment]
> * [x]  已实装
> * [ ]  已测试
> 
> 妖妖梦灵梦 4血 职责: 锁定技，摸牌阶段，你少摸一张牌，观看一名有手牌的其他角色的手牌并获得其中一张牌。 春息: 当你不以此法而获得牌后，你可以展示其中一张红桃牌并选择一名有手牌的其他角色，获得其一张手牌。
> 
> 修改点： 削弱二技能，改成不通过二技能的情况获得红桃牌时可以发动，解除一个回合内不能对同一个抢牌的限制。

妖梦对自己发动“斩妄”时，只能选择弃牌，不能选择加伤。
