### ISSUE TITLE
新将露易兹

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#88]
露易兹   势力：旧    体力上限：4
越界：当仅一张牌置入你的一个区域后，你可以与一名你与其该区域里牌数之差不大于X（X为你已损失的体力值+1）的其他角色交换此区域的牌。每回合限一次。

**Comment by Fsu0413** [comment]
实装完了，我这边没看到什么问题
@MataraOkina 没问题就关了

**Comment by MataraOkina** [comment]
暂时没
