### ISSUE TITLE
如何编译?

### ISSUE THREAD

**Issue by mcthp** [lwtmusou/touhoukill#89]
根据https://github.com/gaodayihao/QSanguosha/wiki/%E6%95%99%E7%A8%8B-Linux%E7%BC%96%E8%AF%91 ,执行make -f linux.mk后报错:
In file included from src/ui/choosegeneralbox.cpp:21:
src/ui/choosegeneralbox.h:27:10: fatal error: timedprogressbar.h: No such file or directory
   27 | #include "timedprogressbar.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [linux.mk:4291: choosegeneralbox.o] Error 1

**Comment by Fsu0413** [comment]
linux.mk已不维护。请使用qmake，参考README.releasebuild.

**Comment by mcthp** [comment]
> linux.mk已不维护。请使用qmake，参考README.releasebuild.

根据README.releasebuild操作,用qt creator打开项目build报错

..\touhoukill-master\src\server\room.cpp(2151) : WARNING: todo_Fs: use a new method to deal with askfortriggerorder
..\touhoukill-master\src\server\room.cpp(2229): error C3861: “currentThread”: 找不到标识符
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"”: 返回代码“0x2”
Stop.
19:59:14: 进程"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"退出，退出代码 2 。
Error while building/deploying project QSanguosha (kit: build)
The kit build has configuration issues which might be the root cause for this problem.
When executing step "Make"

**Comment by Fsu0413** [comment]
> ..\touhoukill-master\src\server\room.cpp(2229): error C3861: “currentThread”: 找不到标识符

最新源码已修正。

PS：Debug模式已经不再维护。

**Comment by mcthp** [comment]
> > ..\touhoukill-master\src\server\room.cpp(2229): error C3861: “currentThread”: 找不到标识符
> 
> 最新源码已修正。
> 
> PS：Debug模式已经不再维护。

下载最新源码build报错,貌似缺失qtmaind.lib,Qt5.6.2-Windows-x86-VS2015搜索不到此文件
错误信息:
link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /VERSION:0.10 /MANIFEST:embed /OUT:debug\QSanguosha.exe @C:\Users\11583\AppData\Local\Temp\nmFBB8.tmp
LINK : fatal error LNK1104: 无法打开文件“qtmaind.lib”
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.EXE"”: 返回代码“0x450”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"”: 返回代码“0x2”
Stop.
09:47:30: 进程"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"退出，退出代码 2 。
Error while building/deploying project QSanguosha (kit: gg)
The kit gg has configuration issues which might be the root cause for this problem.
When executing step "Make"
