### ISSUE TITLE
摩多罗隐岐奈

### ISSUE THREAD

**Issue by MataraOkina** [lwtmusou/touhoukill#9]
摩多罗隐岐奈 体力上限：4 势力：璋
[秘仪]：出牌阶段限一次，若你于此阶段内使用过牌，你可以视为使用【调虎离山】。
[昭威]：结束阶段开始时，若你于此回合内使用过的牌数大于X（X为你的手牌数），你可以选择一项：获得一名其他角色的一张牌，然后其摸一张牌；获得至多X名其他角色各一张手牌，然后弃置等量的牌，这些角色各获得其中一张牌。
[主者]：主公技，出牌阶段限一次，你可以令其他璋势力角色选择是否将其一张牌交给你（选是会终止询问）。

**Comment by lwtmusou** [comment]
已装，没仔细测。谁来测一下，测后关掉issue

**Comment by Fsu0413** [comment]
2技能我还要改一下，等我改完

**Comment by Fsu0413** [comment]
上线了
