### ISSUE TITLE
威压/净化ai问题

### ISSUE THREAD

**Issue by mcthp** [lwtmusou/touhoukill#93]
有净化技能的ai面对威压会打光手牌

记录:

暗将/蕾米莉亚 使用了 火攻[￼3]，目标是 露娜/暗将
娜兹玲/寅丸星 发动了“净化”将 吴六剑[￼6] 当成 无懈可击[￼6] 使用
娜兹玲/寅丸星 卸载了 吴六剑[￼6]
暗将/蕾米莉亚 发动了“威压”
风见幽香/蕾米莉亚 展示了武将，主将为 风见幽香，副将为 蕾米莉亚
风见幽香/蕾米莉亚 的武将牌上有单独的阴阳鱼，可以摸一张牌
风见幽香/蕾米莉亚 摸了 1 张牌
由于“威压”的效果，娜兹玲/寅丸星 需要弃置一张与【无懈可击】牌名相同的牌。
由于“威压”的效果，娜兹玲/寅丸星的【无懈可击】无效。
娜兹玲/寅丸星 亮出了牌堆底的 闪[￼2]
娜兹玲/寅丸星 收回了 闪[￼2]
【无懈可击】的目标是 风见幽香/蕾米莉亚 对 露娜/暗将 的锦囊 【火攻】
娜兹玲/寅丸星 发动了“净化”将 桃[￼4] 当成 无懈可击[￼4] 使用
由于“威压”的效果，娜兹玲/寅丸星 需要弃置一张与【无懈可击】牌名相同的牌。
由于“威压”的效果，娜兹玲/寅丸星的【无懈可击】无效。
【无懈可击】的目标是 风见幽香/蕾米莉亚 对 露娜/暗将 的锦囊 【火攻】
娜兹玲/寅丸星 发动了“净化”将 桃[￼8] 当成 无懈可击[￼8] 使用
由于“威压”的效果，娜兹玲/寅丸星 需要弃置一张与【无懈可击】牌名相同的牌。
由于“威压”的效果，娜兹玲/寅丸星的【无懈可击】无效。
【无懈可击】的目标是 风见幽香/蕾米莉亚 对 露娜/暗将 的锦囊 【火攻】
娜兹玲/寅丸星 发动了“净化”将 桃[￼10] 当成 无懈可击[￼10] 使用
由于“威压”的效果，娜兹玲/寅丸星 需要弃置一张与【无懈可击】牌名相同的牌。
由于“威压”的效果，娜兹玲/寅丸星的【无懈可击】无效。
【无懈可击】的目标是 风见幽香/蕾米莉亚 对 露娜/暗将 的锦囊 【火攻】
娜兹玲/寅丸星 发动了“净化”将 闪[￼2] 当成 无懈可击[￼2] 使用
由于“威压”的效果，娜兹玲/寅丸星 需要弃置一张与【无懈可击】牌名相同的牌。
由于“威压”的效果，娜兹玲/寅丸星的【无懈可击】无效。
【无懈可击】的目标是 风见幽香/蕾米莉亚 对 露娜/暗将 的锦囊 【火攻】
露娜/暗将 展示了 五谷丰登[￼3]
风见幽香/蕾米莉亚 弃置了 乐不思蜀[￼6]

**Comment by Fsu0413** [comment]
没bug，ai问题

**Comment by mcthp** [comment]
那我改下标题(

**Comment by lwtmusou** [comment]
已改，关闭
